export function normalizePaymentFromApi(payment) {
  return {
    id: payment.id,
    txId: payment.transactionId,
    usuarioId: payment.userId,
    technicianId: payment.technicianId,
    tecnicoId: payment.technicianId,
    serviceId: payment.serviceId,
    appointmentId: payment.appointmentId,
    servicio: payment.service?.serviceType || payment.service?.description || "Servicio asociado",
    reference: payment.reference,
    referencia: payment.reference,
    fecha: payment.paidAt || payment.createdAt,
    hora: payment.appointment?.time || "",
    valor: payment.amount,
    amount: payment.amount,
    formattedAmount: payment.formattedAmount || payment.montoFormateado,
    platformCommission: payment.platformCommission,
    formattedPlatformCommission: payment.formattedPlatformCommission || payment.comisionPlataformaFormateada,
    technicianEarnings: payment.technicianEarnings,
    formattedTechnicianEarnings: payment.formattedTechnicianEarnings || payment.gananciaTecnicoFormateada,
    medio: payment.method || payment.userPaymentMethod || payment.medioPagoUsuario,
    method: payment.method || payment.userPaymentMethod || payment.medioPagoUsuario,
    userPaymentMethod: payment.userPaymentMethod || payment.medioPagoUsuario || payment.method,
    technicianPaymentMethod: payment.technicianPaymentMethod || payment.medioPagoTecnico,
    paymentMethodsMatch: payment.paymentMethodsMatch ?? payment.metodosCoinciden,
    canPay: payment.canPay ?? payment.puedePagar ?? true,
    paymentBlockedReason: payment.paymentBlockedReason || payment.motivoBloqueoPago || "",
    serviceStatus: payment.serviceStatus || payment.estadoServicio || payment.service?.status || payment.service?.estado || "",
    confirmationAttempts: payment.technicianConfirmationAttempts ?? payment.cantidadIntentosConfirmacion ?? 0,
    requiresAdminReview: Boolean(payment.requiresAdminReview ?? payment.requiereRevisionAdministrador),
    adminObservation: payment.adminObservation || payment.observacionAdministrador || "",
    technicianVerificationStatus: payment.technicianVerificationStatus || payment.verificacionTecnica || "Pendiente",
    estado: payment.status,
    status: payment.status,
    paidAt: payment.paidAt,
    confirmedAt: payment.confirmedAt,
    confirmedByTechnician: payment.confirmedByTechnician,
    clientName: payment.client?.name || "Cliente sin asignar",
    technicianName: payment.technician?.name || "Tecnico sin asignar",
    duration: payment.service?.duration || "No registrada",
    service: payment.service,
    client: payment.client,
    technician: payment.technician,
    appointment: payment.appointment,
  };
}
