export const LEGACY_TABLES = {
  users: "usrs",
  roles: "roles",
  documentTypes: "tipos_documento",
  specialtyAreas: "areas_especialidad",
  employees: "empleados",
  devices: "equipos",
  serviceRequests: "solicitudes_servicio",
  appointments: "citas",
  payments: "pagos",
  comments: "comentarios",
  commentResponses: "respuestas_comentarios",
  notifications: "notificaciones",
  technicianLocations: "ubicaciones_tecnicos",
  statuses: "estados",
  paymentStatuses: "estado_pago",
  paymentMethods: "medios_pago",
  priorities: "prioridades",
  notificationTypes: "tipos_notificacion",
  serviceTypes: "tp_servicios",
};

export const LEGACY_PRIMARY_KEYS = {
  [LEGACY_TABLES.users]: "id_usrs",
  [LEGACY_TABLES.roles]: "id_rol",
  [LEGACY_TABLES.documentTypes]: "id_tipo_doc",
  [LEGACY_TABLES.specialtyAreas]: "id_area",
  [LEGACY_TABLES.employees]: "id",
  [LEGACY_TABLES.devices]: "id_equipo",
  [LEGACY_TABLES.serviceRequests]: "id_solicitud",
  [LEGACY_TABLES.appointments]: "id_cita",
  [LEGACY_TABLES.payments]: "id_pago",
  [LEGACY_TABLES.comments]: "id_comentario",
  [LEGACY_TABLES.commentResponses]: "id_respuesta",
  [LEGACY_TABLES.notifications]: "id_notificacion",
  [LEGACY_TABLES.technicianLocations]: "id_ubicacion",
  [LEGACY_TABLES.statuses]: "id_estado",
  [LEGACY_TABLES.paymentStatuses]: "id_estado",
  [LEGACY_TABLES.paymentMethods]: "id_medio",
  [LEGACY_TABLES.priorities]: "id_prioridad",
  [LEGACY_TABLES.notificationTypes]: "id_tipo_notif",
  [LEGACY_TABLES.serviceTypes]: "id_tp_servicio",
};

