import { LEGACY_TABLES } from "./legacyTables";

export const LEGACY_SCHEMA = {
  [LEGACY_TABLES.users]: [
    "id_usrs",
    "id_tp_doc",
    "nombre",
    "apellido",
    "correo",
    "clave",
    "telefono",
    "direccion",
    "id_area",
    "fecha_registro",
    "id_rol",
    "activo",
  ],
  [LEGACY_TABLES.roles]: ["id_rol", "nombre_rol"],
  [LEGACY_TABLES.documentTypes]: ["id_tipo_doc", "nombre_tipo", "tipo_abreviado"],
  [LEGACY_TABLES.specialtyAreas]: ["id_area", "nombre_area"],
  [LEGACY_TABLES.employees]: ["id", "nombre", "fecha_contratacion", "salario", "telefono", "id_area"],
  [LEGACY_TABLES.devices]: [
    "id_equipo",
    "id_usrs",
    "tipo_equipo",
    "marca_equipo",
    "modelo_equipo",
    "numero_serie",
    "sistema_operativo",
    "fecha_registro",
    "id_estado",
  ],
  [LEGACY_TABLES.serviceRequests]: [
    "id_solicitud",
    "id_usrs",
    "id_equipo",
    "id_tp_servicio",
    "descripcion_problema",
    "id_prioridad",
    "fecha_solicitud",
    "id_estado",
  ],
  [LEGACY_TABLES.appointments]: [
    "id_cita",
    "id_solicitud",
    "id_usrs",
    "fecha",
    "hora",
    "confirmada",
    "id_estado",
  ],
  [LEGACY_TABLES.payments]: [
    "id_pago",
    "id_cita",
    "id_medio",
    "id_estado_pago",
    "id_usrs",
    "monto",
    "fecha_pago",
    "detalle_comprobante",
  ],
  [LEGACY_TABLES.comments]: ["id_comentario", "id_cita", "fecha_comentario", "id_usrs"],
  [LEGACY_TABLES.commentResponses]: [
    "id_respuesta",
    "id_comentario",
    "id_respondedor",
    "texto_respuesta",
    "fecha_respuesta",
  ],
  [LEGACY_TABLES.notifications]: [
    "id_notificacion",
    "id_usrs",
    "id_tipo_notif",
    "titulo",
    "mensaje",
    "leida",
    "fecha_envio",
  ],
  [LEGACY_TABLES.technicianLocations]: [
    "id_ubicacion",
    "id_usrs",
    "latitud",
    "longitud",
    "fecha_registro",
  ],
};

